llm:
  claude:
    api:
      key: <your-anthropic-api-key>
      endpoint: https://api.anthropic.com/v1/messages

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: password
